# Generated by Django 3.2.5 on 2022-11-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('ciudad', models.CharField(max_length=150, verbose_name='Ciudad')),
                ('soporte_actual', models.TextField(max_length=150, verbose_name='Soporte Actual')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Decripción')),
            ],
        ),
    ]
