# Generated by Django 3.2.5 on 2022-11-25 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='formulario',
            table='formulario',
        ),
    ]
