# Generated by Django 3.2.5 on 2022-11-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_alter_formulario_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='facturacion_mensual',
            field=models.CharField(default='5.000.000 a 25.000.000gs', max_length=60, verbose_name='Facturación Mensual'),
            preserve_default=False,
        ),
    ]
