# Generated by Django 3.2.5 on 2022-11-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_formulario_facturacion_mensual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='facturacion_mensual',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Facturación Mensual'),
        ),
    ]
