# Generated by Django 3.2.6 on 2022-11-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_auto_20221129_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='soporte_actual',
            field=models.TextField(choices=[('Soporte Actual?', 'Soporte Actual?'), ('No utilizo ningún sistema', 'No utilizo ningún sistema'), ('Planilla Electrónica Excel, Otros', 'Planilla Electrónica Excel, Otros'), ('Tengo un sistema, pero no satisface mis necesidades', 'Tengo un sistema, pero no satisface mis necesidades'), ('Mejor calidad de soporte técnico', 'Mejor calidad de soporte técnico'), ('Necesito un sistema a medida para mi Empresa', 'Necesito un sistema a medida para mi Empresa'), ('Otros', 'Otros')], default='Soporte Actual?', max_length=150, verbose_name='Soporte Actual'),
        ),
    ]
