# Generated by Django 4.1.3 on 2022-12-05 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0008_auto_20221204_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seguimiento',
        ),
    ]
