# Generated by Django 4.1.3 on 2022-12-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0009_delete_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='estado',
            field=models.CharField(blank=True, choices=[('Nuevo', 'Nuevo'), ('En Atención', 'En Atención'), ('Cuncluido', 'Cuncluido')], default='Nuevo', editable=False, max_length=20, null=True, verbose_name='Estado de Venta'),
        ),
    ]
